[package]
edition      = "2024"
name         = "m5stack-cores3"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "m5stack-hello"
path = "./src/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32s3"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }
critical-section = "1.2.0"
esp-println = { version = "0.17.0", features = ["esp32s3", "uart"], default-features = false }
embedded-hal = "1.0.0"
mipidsi = "0.10.0"
embedded-graphics = "0.8.2"
embedded-hal-bus = "0.3.0"


[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug         = 2
lto           = 'fat'
opt-level     = 's'
