[alias]
check-board = "check -p cores3 --all-features --target xtensa-esp32s3-none-elf -Zbuild-std=core,alloc"
clippy-board = "clippy -p cores3 --all-features --target xtensa-esp32s3-none-elf -Zbuild-std=core,alloc"
